In [1]:
import tensorflow as tf
from tensorflow.keras import Model,layers
import numpy as np
from PIL import Image
from pathlib import Path
import os
import pandas as pd
import tensorflow_hub as hub

In [2]:
PATH = "C:/Users/Lenovo/Desktop/AI/AI_Project/"
LABEL = "CA_fix1_"
test = Image.open(PATH+"nofNormal.jpg")
test_img = np.array(test)
blank = np.array(None)
t_img = np.expand_dims(test_img,axis=0)
t_img.shape

(1, 224, 224, 3)

In [3]:
myModel = tf.keras.models.load_model('Model2/CA_fix1_Incep3_done.h5',custom_objects={'KerasLayer':hub.KerasLayer})
myModel2 = tf.keras.models.load_model('Model2/Ext_fix1_Incep3_done.h5',custom_objects={'KerasLayer':hub.KerasLayer})
myModel3 = tf.keras.models.load_model('Model2/Heart_fix1_Incep3_done.h5',custom_objects={'KerasLayer':hub.KerasLayer})
myModel4 = tf.keras.models.load_model('Model2/Int_fix1_Incep3_done.h5',custom_objects={'KerasLayer':hub.KerasLayer})
myModel5 = tf.keras.models.load_model('Model2/NoF_fix1_Incep3_done.h5',custom_objects={'KerasLayer':hub.KerasLayer})
myModel6 = tf.keras.models.load_model('Model2/Peno_fix1_Incep3_done.h5',custom_objects={'KerasLayer':hub.KerasLayer})
myModel7 = tf.keras.models.load_model('Model2/TB_fix1_Incep3_done.h5',custom_objects={'KerasLayer':hub.KerasLayer})

In [4]:
img_predCA = myModel.predict_proba(t_img)
img_predEXT = myModel2.predict_proba(t_img)
img_predHEART = myModel3.predict_proba(t_img)
img_predINT = myModel4.predict_proba(t_img)
img_predNOF = myModel5.predict_proba(t_img)
img_predPENO = myModel6.predict_proba(t_img)
img_predTB = myModel7.predict_proba(t_img)

In [5]:
print(img_predCA)
print(img_predEXT)
print(img_predHEART)
print(img_predINT)
print(img_predNOF)
print(img_predPENO)
print(img_predTB)
resCA = np.ceil(img_predCA)
resEXT = np.ceil(img_predEXT)
resHEART = np.ceil(img_predHEART)
resINT = np.ceil(img_predINT)
resNOF = np.ceil(img_predNOF)
resPENO = np.ceil(img_predPENO)
resTB = np.ceil(img_predTB)

[[1.0000000e+00 7.1425133e-37]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]


In [6]:
print(resCA)
print(resEXT)
print(resHEART)
print(resINT)
print(resNOF)
print(resPENO)
print(resTB)

[[1. 1.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]


array([[1., 1.]], dtype=float32)